=== hajoui/psniffstat/src/main/java/br/ufsm/psniffstat/XMLProperties.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/XMLProperties"
            xmlns:tns="http://xml.netbeans.org/schema/XMLProperties"
            elementFormDefault="qualified">
    <xsd:element name="sniff2DBData">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Sniffer">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="port"/>
                            <xsd:element name="intervalOfAnalysis"/>
                            <xsd:element name="ammountOfIntervals"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Database">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="dbName"/>
                            <xsd:element name="hostName"/>
                            <xsd:element name="port"/>
                            <xsd:element name="location"/>
                            <xsd:element name="username"/>
                            <xsd:element name="password"/>
                            <xsd:element name="statusFat"/>
                            <xsd:element name="fatTableName"/>
                            <xsd:element name="statusArchive"/>
                            <xsd:element name="archiveTableName"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Filters">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="tcp"/>
                            <xsd:element name="udp"/>
                            <xsd:element name="icmp"/>
                            <xsd:element name="tcpAck"/>
                            <xsd:element name="tcpFin"/>
                            <xsd:element name="tcpSyn"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Sockets">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="status"/>
                            <xsd:element name="port"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== hajoui/psniffstat/src/main/resources/br/ufsm/psniffstat/XMLProperties.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : XMLProperties.xml
    Created on : May 23, 2009, 11:25 AM
    Author     : Tulkas
    Description:
        Purpose of the document follows.
-->

<sniff2DBData  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/XMLProperties'
   xsi:schemaLocation='XMLProperties.xsd'>
    <Sniffer>
        <port>80</port>
        <intervalOfAnalysis>3</intervalOfAnalysis>
        <ammountOfIntervals>-10</ammountOfIntervals>
    </Sniffer>
    <Database>
        <dbName>mysql</dbName>
        <hostName>localhost</hostName>
        <port>3306</port>
        <location>sniff</location>
        <username>tuxtor</username>
        <password>informatica</password>
        <statusFat>1</statusFat>
        <fatTableName>fat</fatTableName>
        <statusArchive>0</statusArchive>
        <archiveTableName>archive</archiveTableName>
    </Database>
    <Filters>
        <tcp>1</tcp>
        <udp>1</udp>
        <icmp>1</icmp>
        <tcpAck>1</tcpAck>
        <tcpFin>1</tcpFin>
        <tcpSyn>1</tcpSyn>
    </Filters>
    <Sockets>
        <status>1</status>
        <port>7000</port>
    </Sockets>
</sniff2DBData>

=== hajoui/psniffstat/src/main/java/br/ufsm/psniffstat/XMLProperties.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : XMLProperties.xml
    Created on : May 23, 2009, 11:25 AM
    Author     : Tulkas
    Description:
        Purpose of the document follows.
-->

<sniff2DBData  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/XMLProperties'
   xsi:schemaLocation='http://xml.netbeans.org/schema/XMLProperties XMLProperties.xsd'>
    <Sniffer>
        <port>80</port>
        <intervalOfAnalysis>1</intervalOfAnalysis>
        <ammountOfIntervals>-1</ammountOfIntervals>
    </Sniffer>
    <Filters>
        <tcp>1</tcp>
        <udp>1</udp>
        <icmp>1</icmp>
        <tcpAck>1</tcpAck>
        <tcpFin>1</tcpFin>
        <tcpSyn>1</tcpSyn>
    </Filters>
    <Sockets>
        <status>1</status>
        <port>7000</port>
    </Sockets>
</sniff2DBData>
